package client

import("context";"encoding/json";"fmt";"net/http";"net/http/httptest";"os";"path/filepath";"strings";"sync/atomic";"testing";"time")
func TestXAITaskSubmissionPollingAndDownload(t *testing.T){
 var posts atomic.Int32;var server *httptest.Server
 server=httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){switch r.URL.Path{
 case "/v1/videos/generations":posts.Add(1);if r.Method!="POST"||r.Header.Get("Authorization")!="Bearer test-key"{t.Error("invalid submission")};var p map[string]any;if err:=json.NewDecoder(r.Body).Decode(&p);err!=nil{t.Error(err)};if p["model"]!="explicit-model"||p["duration"]!=float64(6)||p["aspect_ratio"]!="16:9"{t.Error(p)};fmt.Fprint(w,`{"request_id":"remote-1"}`)
 case "/v1/videos/remote-1":fmt.Fprintf(w,`{"status":"done","video":{"url":%q,"respect_moderation":true}}`,server.URL+"/movie.mp4")
 case "/movie.mp4":if r.Header.Get("Authorization")!=""{t.Error("credential leaked to media")};w.Header().Set("Content-Type","video/mp4");fmt.Fprint(w,"video-payload")
 default:t.Error(r.URL.Path);http.NotFound(w,r)
 }}));defer server.Close()
 opts:=VideoJobOptions{BaseURL:server.URL+"/v1",APIKey:"test-key",Protocol:"xai",Model:"explicit-model",Prompt:"a shot",Seconds:6,AspectRatio:"16:9"}
 job,err:=CreateVideoJob(context.Background(),opts);if err!=nil||job.Status!=VideoStatusQueued{t.Fatal(job,err)};job,err=PollVideoJob(context.Background(),opts,job.ID);if err!=nil||job.Status!=VideoStatusCompleted{t.Fatal(job,err)}
 path:=filepath.Join(t.TempDir(),"video.mp4");if err=SaveVideoJobMedia(context.Background(),opts,job,path,100);err!=nil{t.Fatal(err)};b,_:=os.ReadFile(path);if string(b)!="video-payload"||posts.Load()!=1{t.Fatal(string(b),posts.Load())}
}
func TestCompatibleVideoContentEndpointDropsCredentialsOnRedirect(t *testing.T){
 cdn:=httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){if r.Header.Get("Authorization")!=""{t.Error("auth forwarded")};w.Header().Set("Content-Type","video/mp4");fmt.Fprint(w,"mp4")}));defer cdn.Close()
 api:=httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){if r.Header.Get("Authorization")!="Bearer key"{t.Error("missing API authentication")};if strings.HasSuffix(r.URL.Path,"/content"){http.Redirect(w,r,cdn.URL+"/asset",http.StatusFound);return};if r.Method=="POST"{r.ParseMultipartForm(1<<20);if r.FormValue("model")!="my-video-model"||r.FormValue("seconds")!="4"{t.Error(r.Form)}};fmt.Fprint(w,`{"id":"v-1","status":"completed"}`)}));defer api.Close()
 opts:=VideoJobOptions{BaseURL:api.URL,APIKey:"key",Protocol:"openai-compatible",Model:"my-video-model",Prompt:"test",Seconds:4,Size:"1280x720"};job,err:=CreateVideoJob(context.Background(),opts);if err!=nil{t.Fatal(err)};if err=SaveVideoJobMedia(context.Background(),opts,job,filepath.Join(t.TempDir(),"video.mp4"),100);err!=nil{t.Fatal(err)}
}
func TestVideoTaskDownloadsAreBoundedAndAtomic(t *testing.T){path:=filepath.Join(t.TempDir(),"video.mp4");os.WriteFile(path,[]byte("previous"),0600);job:=VideoJob{Status:VideoStatusCompleted,B64JSON:"MTIzNDU2Nzg5"};if err:=SaveVideoJobMedia(context.Background(),VideoJobOptions{},job,path,4);err==nil{t.Fatal("limit ignored")};b,_:=os.ReadFile(path);if string(b)!="previous"{t.Fatal("failed download replaced good file")};for _,raw:=range []string{"http://example.com/v.mp4","https://127.0.0.1/v.mp4","https://169.254.169.254/v.mp4","file:///etc/passwd"}{if _,err:=openVideoMediaStream(context.Background(),raw,"https://api.example.com");err==nil{t.Fatal(raw)}}}
func TestVideoStatusesAndPollRetryPolicy(t *testing.T){for _,payload:=range []string{`{"id":"a","status":"unknown"}`,`{"id":"../bad","status":"queued"}`,`{"request_id":"a"}`}{if _,err:=decodeVideoJob([]byte(payload),"","openai-compatible",true);err==nil{t.Fatal(payload)}};job,err:=decodeVideoJob([]byte(`{"status":"done","video":{"respect_moderation":false}}`),"a","xai",false);if err!=nil||job.Status!=VideoStatusFailed{t.Fatal(job,err)};if _,ok:=VideoPollRetryDelay(&VideoAPIError{StatusCode:401},1);ok{t.Fatal("auth should not retry")};if delay,ok:=VideoPollRetryDelay(&VideoAPIError{StatusCode:429,RetryAfter:2*time.Minute},1);!ok||delay!=time.Minute{t.Fatal(delay,ok)};if _,ok:=VideoPollRetryDelay(&VideoAPIError{StatusCode:500},5);ok{t.Fatal("unbounded retry")}}
func TestCreateVideoTaskNeverRetriesPaidPOST(t *testing.T){var calls atomic.Int32;server:=httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){calls.Add(1);w.Header().Set("Retry-After","2");w.WriteHeader(503);fmt.Fprint(w,`{"error":{"message":"busy"}}`)}));defer server.Close();_,err:=CreateVideoJob(context.Background(),VideoJobOptions{BaseURL:server.URL,APIKey:"key",Model:"explicit-model",Prompt:"test",Seconds:4});if err==nil||calls.Load()!=1{t.Fatal(err,calls.Load())}}
