// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivatePromptImportListener() {
  return window['go']['backend']['Service']['ActivatePromptImportListener']();
}

export function BeginNativeFileDrag(arg1) {
  return window['go']['backend']['Service']['BeginNativeFileDrag'](arg1);
}

export function BuildBatchOutputPath(arg1, arg2, arg3) {
  return window['go']['backend']['Service']['BuildBatchOutputPath'](arg1, arg2, arg3);
}

export function Cancel(arg1) {
  return window['go']['backend']['Service']['Cancel'](arg1);
}

export function CheckForAppUpdate() {
  return window['go']['backend']['Service']['CheckForAppUpdate']();
}

export function ChooseBatchInputDir() {
  return window['go']['backend']['Service']['ChooseBatchInputDir']();
}

export function ChooseDirectory(arg1) {
  return window['go']['backend']['Service']['ChooseDirectory'](arg1);
}

export function ChooseOutputDir() {
  return window['go']['backend']['Service']['ChooseOutputDir']();
}

export function CompatibilityStatePath() {
  return window['go']['backend']['Service']['CompatibilityStatePath']();
}

export function CreateVideo(arg1) {
  return window['go']['backend']['Service']['CreateVideo'](arg1);
}

export function CropImage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['Service']['CropImage'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteStoredAPIKey(arg1) {
  return window['go']['backend']['Service']['DeleteStoredAPIKey'](arg1);
}

export function Edit(arg1) {
  return window['go']['backend']['Service']['Edit'](arg1);
}

export function ExportHistoryToFile(arg1) {
  return window['go']['backend']['Service']['ExportHistoryToFile'](arg1);
}

export function ExportUpstreamConfigToFile(arg1) {
  return window['go']['backend']['Service']['ExportUpstreamConfigToFile'](arg1);
}

export function FlipImage(arg1, arg2) {
  return window['go']['backend']['Service']['FlipImage'](arg1, arg2);
}

export function Generate(arg1) {
  return window['go']['backend']['Service']['Generate'](arg1);
}

export function GetImagePromptsBaseURL() {
  return window['go']['backend']['Service']['GetImagePromptsBaseURL']();
}

export function GetOutputDir() {
  return window['go']['backend']['Service']['GetOutputDir']();
}

export function GetStoredAPIKey(arg1) {
  return window['go']['backend']['Service']['GetStoredAPIKey'](arg1);
}

export function HandlePromptImportArgs(arg1) {
  return window['go']['backend']['Service']['HandlePromptImportArgs'](arg1);
}

export function HandlePromptImportURL(arg1) {
  return window['go']['backend']['Service']['HandlePromptImportURL'](arg1);
}

export function ImportHistoryFromFile() {
  return window['go']['backend']['Service']['ImportHistoryFromFile']();
}

export function ImportImageFromB64(arg1, arg2) {
  return window['go']['backend']['Service']['ImportImageFromB64'](arg1, arg2);
}

export function ImportPromptByToken(arg1) {
  return window['go']['backend']['Service']['ImportPromptByToken'](arg1);
}

export function ImportUpstreamConfigFromFile() {
  return window['go']['backend']['Service']['ImportUpstreamConfigFromFile']();
}

export function ListBatchInputImages(arg1) {
  return window['go']['backend']['Service']['ListBatchInputImages'](arg1);
}

export function LoadCodexAPIConfig() {
  return window['go']['backend']['Service']['LoadCodexAPIConfig']();
}

export function LoadCompatibilityState() {
  return window['go']['backend']['Service']['LoadCompatibilityState']();
}

export function MediaHandler(arg1) {
  return window['go']['backend']['Service']['MediaHandler'](arg1);
}

export function OpenExternalURL(arg1) {
  return window['go']['backend']['Service']['OpenExternalURL'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['backend']['Service']['OpenFile'](arg1);
}

export function OpenImageDialog() {
  return window['go']['backend']['Service']['OpenImageDialog']();
}

export function OpenImagesDialog() {
  return window['go']['backend']['Service']['OpenImagesDialog']();
}

export function OpenMaskImageDialog() {
  return window['go']['backend']['Service']['OpenMaskImageDialog']();
}

export function OpenOutputDir() {
  return window['go']['backend']['Service']['OpenOutputDir']();
}

export function OptimizePrompt(arg1) {
  return window['go']['backend']['Service']['OptimizePrompt'](arg1);
}

export function PollVideo(arg1) {
  return window['go']['backend']['Service']['PollVideo'](arg1);
}

export function ProbeUpstream(arg1) {
  return window['go']['backend']['Service']['ProbeUpstream'](arg1);
}

export function ReadImageAsBase64(arg1) {
  return window['go']['backend']['Service']['ReadImageAsBase64'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['backend']['Service']['ReadTextFile'](arg1);
}

export function RegisterImportedImageAsset(arg1) {
  return window['go']['backend']['Service']['RegisterImportedImageAsset'](arg1);
}

export function RegisterMediaAsset(arg1, arg2) {
  return window['go']['backend']['Service']['RegisterMediaAsset'](arg1, arg2);
}

export function RegisterTrustedOutputDir(arg1) {
  return window['go']['backend']['Service']['RegisterTrustedOutputDir'](arg1);
}

export function RotateImage(arg1, arg2) {
  return window['go']['backend']['Service']['RotateImage'](arg1, arg2);
}

export function SaveCompatibilityState(arg1) {
  return window['go']['backend']['Service']['SaveCompatibilityState'](arg1);
}

export function SaveImageAs(arg1, arg2) {
  return window['go']['backend']['Service']['SaveImageAs'](arg1, arg2);
}

export function SaveImagePathAs(arg1, arg2) {
  return window['go']['backend']['Service']['SaveImagePathAs'](arg1, arg2);
}

export function SaveImagePathToDir(arg1, arg2, arg3) {
  return window['go']['backend']['Service']['SaveImagePathToDir'](arg1, arg2, arg3);
}

export function SaveImageToDir(arg1, arg2, arg3) {
  return window['go']['backend']['Service']['SaveImageToDir'](arg1, arg2, arg3);
}

export function SetCleanupPreviewCacheOnExitEnabled(arg1) {
  return window['go']['backend']['Service']['SetCleanupPreviewCacheOnExitEnabled'](arg1);
}

export function SetKeepLogsEnabled(arg1) {
  return window['go']['backend']['Service']['SetKeepLogsEnabled'](arg1);
}

export function SetOutputDir(arg1) {
  return window['go']['backend']['Service']['SetOutputDir'](arg1);
}

export function SetStoredAPIKey(arg1, arg2) {
  return window['go']['backend']['Service']['SetStoredAPIKey'](arg1, arg2);
}

export function UpscaleImage(arg1, arg2) {
  return window['go']['backend']['Service']['UpscaleImage'](arg1, arg2);
}

export function WriteAppUpdateProbe(arg1) {
  return window['go']['backend']['Service']['WriteAppUpdateProbe'](arg1);
}
