// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {studio} from '../models';
import {http} from '../models';
import {context} from '../models';

export function CancelJob(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeletePromptCard(arg1:string,arg2:number):Promise<void>;

export function GetChanges(arg1:string,arg2:number):Promise<studio.ChangeSet>;

export function GetPublicPromptCatalog(arg1:string):Promise<string>;

export function GetSnapshot():Promise<studio.Snapshot>;

export function ImportImage(arg1:string,arg2:string):Promise<studio.Asset>;

export function ImportPromptCards(arg1:Array<studio.PromptCard>):Promise<Array<studio.PromptCard>>;

export function MediaHandler(arg1:http.Handler):Promise<http.Handler>;

export function ResumeJob(arg1:string):Promise<void>;

export function RunWorkflow(arg1:string,arg2:string,arg3:string):Promise<Array<studio.Job>>;

export function SaveAsset(arg1:string):Promise<boolean>;

export function SaveProfile(arg1:studio.Profile,arg2:string):Promise<studio.Profile>;

export function SaveProject(arg1:studio.Project):Promise<studio.Project>;

export function SavePromptCard(arg1:studio.PromptCard):Promise<studio.PromptCard>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function SubmitGeneration(arg1:studio.Request):Promise<studio.Job>;

export function TestProfile(arg1:string):Promise<Array<string>>;
