// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyDLSS5(arg1, arg2) {
  return window['go']['backend']['StudioV2']['ApplyDLSS5'](arg1, arg2);
}

export function ArchiveJobs(arg1) {
  return window['go']['backend']['StudioV2']['ArchiveJobs'](arg1);
}

export function CancelDLSS5(arg1) {
  return window['go']['backend']['StudioV2']['CancelDLSS5'](arg1);
}

export function CancelDLSS5Preview(arg1) {
  return window['go']['backend']['StudioV2']['CancelDLSS5Preview'](arg1);
}

export function CancelJob(arg1) {
  return window['go']['backend']['StudioV2']['CancelJob'](arg1);
}

export function ClearProfileKey(arg1) {
  return window['go']['backend']['StudioV2']['ClearProfileKey'](arg1);
}

export function DeleteJob(arg1) {
  return window['go']['backend']['StudioV2']['DeleteJob'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['backend']['StudioV2']['DeleteProfile'](arg1);
}

export function DeletePromptCard(arg1, arg2) {
  return window['go']['backend']['StudioV2']['DeletePromptCard'](arg1, arg2);
}

export function DuplicateProfile(arg1) {
  return window['go']['backend']['StudioV2']['DuplicateProfile'](arg1);
}

export function GetChanges(arg1, arg2) {
  return window['go']['backend']['StudioV2']['GetChanges'](arg1, arg2);
}

export function GetProfileKey(arg1) {
  return window['go']['backend']['StudioV2']['GetProfileKey'](arg1);
}

export function GetPublicPromptCatalog(arg1) {
  return window['go']['backend']['StudioV2']['GetPublicPromptCatalog'](arg1);
}

export function GetSnapshot() {
  return window['go']['backend']['StudioV2']['GetSnapshot']();
}

export function ImportClassicProfiles(arg1) {
  return window['go']['backend']['StudioV2']['ImportClassicProfiles'](arg1);
}

export function ImportImage(arg1, arg2) {
  return window['go']['backend']['StudioV2']['ImportImage'](arg1, arg2);
}

export function ImportPromptCards(arg1) {
  return window['go']['backend']['StudioV2']['ImportPromptCards'](arg1);
}

export function ListProfiles() {
  return window['go']['backend']['StudioV2']['ListProfiles']();
}

export function MediaHandler(arg1) {
  return window['go']['backend']['StudioV2']['MediaHandler'](arg1);
}

export function PreviewDLSS5(arg1) {
  return window['go']['backend']['StudioV2']['PreviewDLSS5'](arg1);
}

export function ProbeDLSS5() {
  return window['go']['backend']['StudioV2']['ProbeDLSS5']();
}

export function RestoreAsset(arg1) {
  return window['go']['backend']['StudioV2']['RestoreAsset'](arg1);
}

export function RestoreProject(arg1) {
  return window['go']['backend']['StudioV2']['RestoreProject'](arg1);
}

export function ResumeJob(arg1) {
  return window['go']['backend']['StudioV2']['ResumeJob'](arg1);
}

export function RetryDLSS5(arg1) {
  return window['go']['backend']['StudioV2']['RetryDLSS5'](arg1);
}

export function RunWorkflow(arg1, arg2, arg3) {
  return window['go']['backend']['StudioV2']['RunWorkflow'](arg1, arg2, arg3);
}

export function SaveAsset(arg1) {
  return window['go']['backend']['StudioV2']['SaveAsset'](arg1);
}

export function SaveProfile(arg1, arg2) {
  return window['go']['backend']['StudioV2']['SaveProfile'](arg1, arg2);
}

export function SaveProject(arg1) {
  return window['go']['backend']['StudioV2']['SaveProject'](arg1);
}

export function SavePromptCard(arg1) {
  return window['go']['backend']['StudioV2']['SavePromptCard'](arg1);
}

export function SetNetworkProxy(arg1, arg2) {
  return window['go']['backend']['StudioV2']['SetNetworkProxy'](arg1, arg2);
}

export function Shutdown(arg1) {
  return window['go']['backend']['StudioV2']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['backend']['StudioV2']['Startup'](arg1);
}

export function SubmitGeneration(arg1) {
  return window['go']['backend']['StudioV2']['SubmitGeneration'](arg1);
}

export function TestProfile(arg1) {
  return window['go']['backend']['StudioV2']['TestProfile'](arg1);
}

export function TrashAsset(arg1) {
  return window['go']['backend']['StudioV2']['TrashAsset'](arg1);
}

export function TrashProject(arg1) {
  return window['go']['backend']['StudioV2']['TrashProject'](arg1);
}
